server:
    port: 9999

#person:
#  age: 18
#  boss: false
#  birthday: 1998/04/16
#  maps: {k1: 11,k2: 22}
#  lists:
#    - list1
#    - list2
#    - list3
#  dog:
#    age: 2
#    name: xiaobai
#  last-name: xixihuahua


